CREATE TYPE color AS enum (
    'orange',
    'black',
    'white',
    'grey',
    'colourful'
    );

CREATE TABLE IF NOT EXISTS cats (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name VARCHAR(255),
                                    breed VARCHAR(255),
                                    color VARCHAR(255),
                                    owner_id BIGINT NOT NULL,
                                    birthday DATE);
CREATE TABLE IF NOT EXISTS friends (
                                       first_cat_id BIGINT NOT NULL,
                                       second_cat_id BIGINT NOT NULL,
                                       primary key(first_cat_id, second_cat_id)
);

CREATE TABLE IF NOT EXISTS owners (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                                      birthday DATE
);