create table users (
    id BIGINT GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY NOT NULL,
    owner_id BIGINT REFERENCES owners(id),
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL
);
create table authorities (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                             authority VARCHAR(255) not null
);
create table user_authorities (
                                  user_id BIGINT not null REFERENCES users(id),
                                  authority_id BIGINT not null REFERENCES authorities(id)
);